services:
  postgres:
    image: postgres:16
    container_name: stockpilot_postgres
    restart: always
    environment:
      POSTGRES_USER: stockpilot
      POSTGRES_PASSWORD: stockpilot_secret
      POSTGRES_DB: stockpilot_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U stockpilot -d stockpilot_db']
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: stockpilot_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  mailpit:
    image: axllent/mailpit
    container_name: stockpilot_mailpit
    restart: always
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  postgres_data:
  minio_data:
